# =============================================================================
# SonarCloud — configuration du projet
# =============================================================================

sonar.projectKey=evanferron_rust-api-template
sonar.organization=evanferron

sonar.projectName=rust-api-template
sonar.projectVersion=1.0

# Sources analysées
sonar.sources=src
sonar.exclusions=src/bin/**,**/schema.rs
sonar.host.url=https://sonarcloud.io

sonar.rust.coverage.reportPaths=coverage.xml

# Langue
sonar.language=rust